# Heuristic evaluation weights — will be tuned via self-play later.

SCORE_DELTA_W = 1.0
CARPET_POTENTIAL_W = 0.8
FUTURE_CARPET_W = 0.5
MOBILITY_W = 0.1
SETUP_DISTANCE_W = -0.05
DEAD_PRIME_PENALTY_W = -0.3
SEARCH_EV_BEST_W = 0.6
BELIEF_ENTROPY_W = -0.02
OPPONENT_DISRUPTION_W = 0.15
TIME_PRESSURE_W = -0.01
BLOCKED_CORNER_W = 0.05
